Add a test case for and fix #1571
bluejekyll/trust-dns pull request #1594
Opened 2021-11-23 22:56 UTC by saethlin

2021-11-29 18:56 UTC, bluejekyll commented
I haven't looked into why this is failing, but just wanted to make sure you saw this

```
thread 'op::message::test_emit_and_read_records' panicked at 'called `Result::unwrap()` on an `Err` value: ProtoError { kind: IncorrectRDataLengthRead { read: 4, len: 0 }, backtrack: None }', crates/proto/src/op/message.rs:1066:43
```

2021-11-29 19:48 UTC, saethlin commented
I did not see that. I'll look at this later today or tomorrow.

2021-12-01 00:45 UTC, saethlin commented
@bluejekyll The test failure is related to this code:
https://github.com/bluejekyll/trust-dns/blob/b627283df67fa0cc73669d5cd5c8c2059f7992f9/crates/proto/src/rr/resource.rs#L95-L100

It looks to me like this is constructing an invalid `Record`. The record type and data don't match. I think previously this was fine, because of the special-casing of `RData::NULL`; before this PR the presence of that causes the rdlength field to be zero and thus the rr_type field to be ignored.

I've added a commit to make the `Default` fields consistent.

2021-12-02 05:10 UTC, saethlin commented
🤦 I keep forgetting to run with `--all-features` I guess

2021-12-11 22:32 UTC, bluejekyll commented
I just took a quick look at this. I think we have a problem with having more strict record requirements and dynamic DNS which I remember plays a little fast-and-loose with records to express operations.

2021-12-11 22:42 UTC, bluejekyll requested changes

2021-12-11 22:42 UTC, bluejekyll commented on crates/proto/src/rr/resource.rs
> -        // this is to handle updates, RFC 2136, which uses 0 to indicate certain aspects of
lol, how did I miss this comment in the previous review... it explains why we allow NULL here: 

`this is to handle updates, RFC 2136, which uses 0 to indicate certain aspects of pre-requisites`

i.e. this is perfectly valid, and in-fact, required for Dynamic DNS. I believe a NULL rdata with a type in Dynamic DNS is a prereq check (or delete operation) for a name with any value for the RDATA section, for matching. So we'll need to rethink the fix for this.

2022-01-14 14:31 UTC, saethlin commented
Subsumed by #1605

2022-01-14 14:31 UTC, closed without merging