Allow customizing the static hosts configuration
bluejekyll/trust-dns pull request #1705
Opened 2022-05-01 20:09 UTC by fantix

This allows custom runtimes to provide the hosts configuration in their
own way, like using io_uring instead of the `std::fs::File::open()` to
read the system hosts file.

2022-05-02 03:02 UTC, bluejekyll requested changes
A couple of minor things. Overall this looks good. Thanks for putting up the PR.

2022-05-02 03:02 UTC, bluejekyll commented on crates/resolver/src/hosts.rs
> +                .unwrap_or_default();
Let's return this error.

2022-05-02 13:14 UTC, fantix commented on crates/resolver/src/hosts.rs
> +impl Hosts {
Ah, I was trying to keep the git history/diff, but looks like the indent is anyway breaking it, so I'll move it up then.

2022-05-02 13:22 UTC, fantix commented on crates/resolver/src/hosts.rs
> +    pub fn read_hosts_conf(mut self, src: impl io::Read) -> Self {
Makes sense, fixed for this case!

2022-05-08 19:54 UTC, bluejekyll approved these changes
Looks good. Sorry for the delay.

2022-05-08 19:54 UTC, merged

2022-05-09 00:29 UTC, fantix commented
Totally understandable, thanks a lot for merging! It’s pretty exciting to see trust-dns working under io_uring through Cython in my [toy project](https://gitee.com/fantix/kloop) for asyncio, it’s only possible because you did a great job with trust-dns!

2022-05-09 03:35 UTC, bluejekyll commented
I've had a lot of help from people like you. Thank you!